import Head from "next/head"
import style from '../styles/layout.module.css';
import Menu from "./menu";

export default function Layout({children, title}){
    return<dive>
        <Head>
        <title>Food store {title ? '| ${title}' : ""}</title>
\\corregir comillas de title
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <div className={style.container}>{children}</div>
    </dive>
}